version: "3.7"

services:
  server-db:
    image: postgres:12.10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_NAME: likedao
      DATABASE_USER: likedao
      DATABASE_PASSWORD: likedao
      DATABASE_SCHEMA: likedao
    volumes:
      - server-db_data:/var/lib/postgresql/data
      - ./graphql-server/initdb.d/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
  bdjuno-db:
    image: postgres:12.4
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_NAME: bdjuno
      DATABASE_USER: bdjuno
      DATABASE_PASSWORD: bdjuno
      DATABASE_SCHEMA: bdjuno
    volumes:
      - ./bdjuno/bdjuno/database/schema/:/var/src/schemas:ro
      - bdjuno-db_data:/var/lib/postgresql/data
      - ./bdjuno/initdb.d/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
  graphql-server:
    depends_on:
      - server-db
    build:
      context: ./graphql-server
      dockerfile: ./Dockerfile.dev
    env_file:
      - ./graphql-server/.env
    volumes:
      - ./graphql-server:/usr/src/app
    ports:
      - "8080:8080"
  bdjuno:
    depends_on:
      - bdjuno-db
    build:
      context: ./bdjuno/bdjuno
      dockerfile: ./Dockerfile
    restart: always
    command: bdjuno start --home /bdjuno/.bdjuno
    volumes:
      - ./bdjuno/.bdjuno:/bdjuno/.bdjuno

volumes:
  server-db_data:
    driver: local
  bdjuno-db_data:
    driver: local
