host: likedao.example.com
graphqlServer:
  imageName: ghcr.io/oursky/likedao-graphql-server
  session:
    cookieDomain: likedao.example.com
    signatureSecret: "__SESSION_SECRET__"
    nonceExpiry: 3600
    sessionExpiry: 86400
  sentry:
    dsn: dsn
  corsAllowOrigins: "*"
  serverDatabase:
    url: postgres://likedao:likedao@server-db/likedao?sslmode=disable
    schema: likedao
    poolSize: 5
  bdjunoDatabase:
    url: postgres://likedao:likedao@bdjuno-db/bdjuno?sslmode=disable
    schema: bdjuno
    poolSize: 5
  chain:
    coinDenom: nanolike
    bech32Prefix: like
reactApp:
  imageName: ghcr.io/oursky/likedao-react-app
  sentry:
    dsn: dsn
  chainId: likecoin-mainnet-2
  chainRpc: https://mainnet-node.like.co:443/rpc/
  chainRest: https://mainnet-node.like.co
  graphqlEndpoint: http://localhost:8080/graphql
  authEndpoint: http://localhost:8080/auth
  chainLinks:
    - chainId: likecoin-mainnet-2
      link: http://localhost:3000
  footerLinks:
    githubLink: https://github.com/likecoin/likedao
    tokenLinks:
      - name: osmosis
        link: https://app.osmosis.zone/?from=OSMO&to=LIKE
    contactSupport: https://go.crisp.chat/chat/embed/?website_id=5c009125-5863-4059-ba65-43f177ca33f7
  bech32Config:
    bech32PrefixAccAddr: like
    bech32PrefixAccPub: likepub
    bech32PrefixValAddr: likevaloper
    bech32PrefixValPub: likevaloperpub
    bech32PrefixConsAddr: likevalcons
    bech32PrefixConsPub: likevalconspub
  currency:
    coinDenom: LIKE
    coinMinimalDenom: nanolike
    coinDecimals: 9
    geckoId: likecoin
  walletConnect:
    gasPrice: 10nanolike
  keplr:
    chainId: likecoin-mainnet-2
    chainName: Likecoin Chain
    walletUrlForStaking: https://stake.like.co
    coinType: 118
    gasPriceStep:
      low: 1
      average: 10
      high: 1000

bdjuno:
  imageName: ghcr.io/oursky/likedao-bdjuno
  genesisUrl: https://raw.githubusercontent.com/likecoin/mainnet/master/genesis.json
  config:
    loggingLevel: debug
    chain:
      bech32Prefix:
        - like
        - cosmos
      additionalModules:
    rpc:
      clientName: juno
      address: https://mainnet-node-rpc.like.co:443
      maxConnections: 20
    grpc:
      address: mainnet-node-grpc.like.co:80
    parsing:
      workers: 4
      startHeight: 1
      averageBlockTime: 6s
    database:
      name: bdjuno
      host: bdjuno-db
      port: 5432
      user: bdjuno
      password: bdjuno
      schema: bdjuno
      maxConnections: 1
      partitionSize: 100000
      partitionBatch: 1000
  resources:
    limits:
      cpu: 2
      memory: 1792Mi
    requests:
      cpu: 2
      memory: 1792Mi
