apiVersion: v1
kind: Service
metadata:
  labels:
    app: graphql-server-{{ .Values.deploymentTag }}
    app.kubernetes.io/name: graphql-server-{{ .Values.deploymentTag }}
    app.kubernetes.io/instance: graphql-server-{{ .Values.deploymentTag }}
  name: graphql-server-{{ .Values.deploymentTag }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: graphql-server-{{ .Values.deploymentTag }}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-server-{{ .Values.deploymentTag }}
  labels:
    app: graphql-server-{{ .Values.deploymentTag }}
spec:
  selector:
    matchLabels:
      app: graphql-server-{{ .Values.deploymentTag }}
  replicas: 1
  template:
    metadata:
      labels:
        app: graphql-server-{{ .Values.deploymentTag }}
    spec:
      restartPolicy: Always
      containers:
        - name: graphql-server
          image: {{ .Values.graphqlServer.imageName }}:{{ .Values.buildTag }}
          command: ["/usr/likedao/bin/graphql-server"]
          ports:
            - containerPort: 8080
          env:
            - name: GIN_MODE
              value: release
            - name: GRAPHQL_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: graphql-server-config-{{ .Values.deploymentTag }}
                  key: GRAPHQL_SENTRY_DSN
            - name: GRAPHQL_SENTRY_ENVIRONMENT
              value: {{ .Values.deploymentTag }}
            - name: SERVER_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: graphql-server-config-{{ .Values.deploymentTag }}
                  key: SERVER_DATABASE_URL
            - name: BDJUNO_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: graphql-server-config-{{ .Values.deploymentTag }}
                  key: BDJUNO_DATABASE_URL
            - name: SERVER_DATABASE_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: graphql-server-config-{{ .Values.deploymentTag }}
                  key: SERVER_DATABASE_SCHEMA
            - name: CHAIN_COIN_DENOM
              valueFrom:
                secretKeyRef:
                  name: graphql-server-config-{{ .Values.deploymentTag }}
                  key: CHAIN_COIN_DENOM
            - name: CHAIN_BECH32_PREFIX
              valueFrom:
                secretKeyRef:
                  name: graphql-server-config-{{ .Values.deploymentTag }}
                  key: CHAIN_BECH32_PREFIX
            - name: BDJUNO_DATABASE_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: graphql-server-config-{{ .Values.deploymentTag }}
                  key: BDJUNO_DATABASE_SCHEMA
            - name: CORS_ALLOW_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: graphql-server-config-{{ .Values.deploymentTag }}
                  key: CORS_ALLOW_ORIGINS
            - name: SIGNATURE_SECRET
              valueFrom:
                secretKeyRef:
                  name: graphql-server-config-{{ .Values.deploymentTag }}
                  key: SIGNATURE_SECRET
            - name: COOKIE_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: graphql-server-config-{{ .Values.deploymentTag }}
                  key: COOKIE_DOMAIN
            - name: SERVER_DATABASE_POOL_SIZE
              value: {{ .Values.graphqlServer.serverDatabase.poolSize | quote }}
            - name: BDJUNO_DATABASE_POOL_SIZE
              value: {{ .Values.graphqlServer.bdjunoDatabase.poolSize | quote }}
            - name: NONCE_EXPIRY
              value: {{ .Values.graphqlServer.session.nonceExpiry | quote }}
            - name: SESSION_EXPIRY
              value: {{ .Values.graphqlServer.session.sessionExpiry | quote }}
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: graphql-server-config-{{ .Values.deploymentTag }}
type: Opaque
data:
  CORS_ALLOW_ORIGINS: {{ .Values.graphqlServer.corsAllowOrigins | b64enc }}
  CHAIN_BECH32_PREFIX: {{ .Values.graphqlServer.chain.bech32Prefix | b64enc }}
  CHAIN_COIN_DENOM: {{ .Values.graphqlServer.chain.coinDenom | b64enc }}
  SERVER_DATABASE_URL: {{ .Values.graphqlServer.serverDatabase.url | b64enc }}
  SERVER_DATABASE_SCHEMA: {{ .Values.graphqlServer.serverDatabase.schema | b64enc }}
  BDJUNO_DATABASE_URL: {{ .Values.graphqlServer.bdjunoDatabase.url | b64enc }}
  BDJUNO_DATABASE_SCHEMA: {{ .Values.graphqlServer.bdjunoDatabase.schema | b64enc }}
  GRAPHQL_SENTRY_DSN: {{ .Values.graphqlServer.sentry.dsn | b64enc }}
  SIGNATURE_SECRET: {{ .Values.graphqlServer.session.signatureSecret | b64enc }}
  COOKIE_DOMAIN: {{ .Values.graphqlServer.session.cookieDomain | b64enc }}