apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: likedao-{{ .Values.deploymentTag }}
  name: likedao-{{ .Values.deploymentTag }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /
            backend:
              service:
                name: react-app-{{ .Values.deploymentTag }}
                port:
                  number: 80
          - pathType: ImplementationSpecific
            path: /graphql
            backend:
              service:
                name: graphql-server-{{ .Values.deploymentTag }}
                port:
                  number: 80
          - pathType: ImplementationSpecific
            path: /auth
            backend:
              service:
                name: graphql-server-{{ .Values.deploymentTag }}
                port:
                  number: 80
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: likedao-tls-{{ .Values.deploymentTag }}