apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-app-{{ .Values.deploymentTag }}
  name: react-app-{{ .Values.deploymentTag }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: react-app-{{ .Values.deploymentTag }}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-{{ .Values.deploymentTag }}
  labels:
    app: react-app-{{ .Values.deploymentTag }}
spec:
  selector:
    matchLabels:
      app: react-app-{{ .Values.deploymentTag }}
  replicas: 1
  template:
    metadata:
      labels:
        app: react-app-{{ .Values.deploymentTag }}
      annotations:
        checksum/nginx-config: {{ include (print $.Template.BasePath "/react-app.nginx.yaml") . | sha256sum }}
        checksum/keplr-config: {{ include (print $.Template.BasePath "/react-app.keplr.yaml") . | sha256sum }}
        checksum/server-config: {{ include (print $.Template.BasePath "/react-app.config.yaml") . | sha256sum }}
    spec:
      restartPolicy: Always
      containers:
        - name: react-app
          image: {{ .Values.reactApp.imageName }}:{{ .Values.buildTag }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: react-app-nginx-conf-{{ .Values.deploymentTag }}
              mountPath: /etc/nginx/conf.d/nginx.conf
              subPath: nginx.conf
            - name: react-app-config-{{ .Values.deploymentTag }}
              mountPath: /usr/share/config/config.js
              subPath: config.js
            - name: react-app-keplr-{{ .Values.deploymentTag }}
              mountPath: /usr/share/config/keplr.js
              subPath: keplr.js
          readinessProbe:
            httpGet:
              path: /ping
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /ping
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
      volumes:
        - name: react-app-nginx-conf-{{ .Values.deploymentTag }}
          configMap:
            name: react-app-nginx-conf-{{ .Values.deploymentTag }}
        - name: react-app-config-{{ .Values.deploymentTag }}
          configMap:
            name: react-app-config-{{ .Values.deploymentTag }}
        - name: react-app-keplr-{{ .Values.deploymentTag }}
          configMap:
            name: react-app-keplr-{{ .Values.deploymentTag }}