apiVersion: v1
kind: ConfigMap
metadata:
  name: react-app-nginx-conf-{{ .Values.deploymentTag }}
data:
  nginx.conf: |
    server {
      listen 80;

      gzip on;
      gzip_proxied any;
      gzip_min_length 1000;
      gzip_types
          application/json
          text/plain
          text/css
          text/js
          text/xml
          text/javascript
          application/javascript
          application/x-javascript
          image/svg+xml;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
          try_files $uri $uri/ /index.html;
      }

      location = /config.js {
          expires 5m;
          alias /usr/share/config/config.js;
      }

      location = /keplr.js {
        expires 5m;
        alias /usr/share/config/keplr.js;
      }

      location = /ping {
          add_header Content-Type text/plain;
          return 200 'pong';
      }
    }
